module.exports={
CART_COLLECTION:'cart',
USER_COLLECTION:'user',
PRODUCT_COLLECTION:'product',
ORDER_COLLECTION:'order',
CATEGORY_COLLECTION:'category',
WISHLIST_COLLECTION:'wishlist',
ADDRESS_COLLECTION:'address',
RETURN_COLLECTION:'return',
COUPON_COLLECTION:'coupon',
BRAND_COLLECTION:'brand',
USED_COUPON_COLLECTION:'usedcoupon'

}